atomi/workspace:
  active: true
  history:
    - version: 27
      time: 2026-02-23T18:50:49.607882Z
      answers:
        atomi/workspace/platform:
          type: String
          value: samples
        atomi/workspace/enable-docker:
          type: Bool
          value: false
        atomi/workspace/enable-helm:
          type: Bool
          value: false
        atomi/workspace/service:
          type: String
          value: bun-lib
        atomi/workspace/enable-secret:
          type: Bool
          value: true
        atomi/workspace/runtime:
          type: String
          value: Bun
      deterministic_states: {}
    - version: 27
      time: 2026-02-23T18:53:36.105054Z
      answers:
        atomi/workspace/enable-docker:
          type: Bool
          value: false
        atomi/workspace/platform:
          type: String
          value: samples
        atomi/workspace/enable-secret:
          type: Bool
          value: false
        atomi/workspace/enable-helm:
          type: Bool
          value: false
        atomi/workspace/runtime:
          type: String
          value: Bun
        atomi/workspace/service:
          type: String
          value: bun-lib
      deterministic_states: {}
    - version: 28
      time: 2026-02-23T23:33:49.434491Z
      answers:
        atomi/workspace/runtime:
          type: String
          value: Bun
        atomi/workspace/platform:
          type: String
          value: samples
        atomi/workspace/service:
          type: String
          value: bun-lib
        atomi/workspace/enable-secret:
          type: Bool
          value: false
        atomi/workspace/enable-helm:
          type: Bool
          value: false
        atomi/workspace/enable-docker:
          type: Bool
          value: false
      deterministic_states: {}
    - version: 29
      time: 2026-02-25T02:59:26.958579Z
      answers:
        atomi/workspace/enable-secret:
          type: Bool
          value: false
        atomi/workspace/service:
          type: String
          value: bun-lib
        atomi/workspace/platform:
          type: String
          value: samples
        atomi/workspace/enable-helm:
          type: Bool
          value: false
        atomi/workspace/enable-docker:
          type: Bool
          value: false
        atomi/workspace/runtime:
          type: String
          value: Bun
      deterministic_states: {}
    - version: 30
      time: 2026-02-25T04:24:21.490780Z
      answers:
        atomi/workspace/enable-secret:
          type: Bool
          value: false
        atomi/workspace/enable-docker:
          type: Bool
          value: false
        atomi/workspace/runtime:
          type: String
          value: Bun
        atomi/workspace/service:
          type: String
          value: bun-lib
        atomi/workspace/enable-helm:
          type: Bool
          value: false
        atomi/workspace/platform:
          type: String
          value: samples
      deterministic_states: {}
atomi/shared:
  active: true
  history:
    - version: 2
      time: 2026-02-24T05:22:18.617584Z
      answers: {}
      deterministic_states: {}
    - version: 3
      time: 2026-02-25T03:00:10.236130Z
      answers: {}
      deterministic_states: {}
    - version: 4
      time: 2026-02-25T04:22:16.857373Z
      answers: {}
      deterministic_states: {}
atomi/nix-init:
  active: true
  history:
    - version: 24
      time: 2026-02-23T18:49:34.126033Z
      answers:
        runtime:
          type: String
          value: Bun
        platform:
          type: String
          value: samples
        service:
          type: String
          value: bun-lib
        init-type:
          type: String
          value: AtomiCloud Suite
        infra:
          type: Bool
          value: false
      deterministic_states: {}
