version: '3'

tasks:
  setup:
    desc: 'Setup the repository'
    cmds: #
      - bun install
      #
      #
  lint:
    desc: Lints the whole code-base
    cmds:
      - pre-commit run --all
  #
  deadcode:
    desc: 'Find code only used by tests or not used at all (requires verification)'
    cmds: #
      - bun knip --include classMembers,types
      #
  #
